[package]
name = "generate_logs"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
indicatif = "0.17"

[profile.release]
lto = true
codegen-units = 1
